### PR TITLE
Fix problem with redirects in Safari by removing spurious slash.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Possible fix for #54.
@michaelaye, are you able to check out this branch and install it locally to see if this fixes your problem? You would install it by running
```
jlpm install
jlpm run build
jupyter labextension install .
```
from the repository directory.

### CODE REVIEW

**Comment by michaelaye** [comment]
I don't find `jlpm` in conda?

**Comment by ian-r-rose** [comment]
Yes, `jlpm` is an alias to the `yarn` that is distributed with JupyterLab for the purposes of extension installation.

**Comment by jasongrout** [comment]
"jlpm" = "JupyterLab package manager"

**Comment by ian-r-rose** [comment]
@michaelaye has confirmed that this fixes the issue with Safari (thanks!)

**Comment by ian-r-rose** [comment]
@michaelaye  I have just released a patch with this fix.

**Pull request merged**
