### PR TITLE
copy request for get_next_page

### PR DESCRIPTION
**Pull request by ktong**
Copy from last request for get_next_page so information like Authorization do not lose.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Can you describe where the Authorization was coming from previously, and whether we could add it in the constructor? I think I would prefer to create a new `HTTPRequest` correctly rather than copying the previous one.

**Comment by ktong** [comment]
Our GHE only supports basic authentication. So we set the api_url as https://<username>:<password>@host/api/v3/. The AsyncHttpClient in Tornado converts <username>:<password> to "Authorization" header and set it into request. 

However, there is no <username>:<password> in next_page link which causes 401 response.

**Comment by ktong** [comment]
FYI, tornado simple_httpclient copies request for following redirect request. https://github.com/tornadoweb/tornado/blob/master/tornado/simple_httpclient.py#L493

**Comment by ian-r-rose** [comment]
Interesting. Okay, you've convinced me. Thanks @ktong!

**Comment by ian-r-rose** [comment]
I plan to release the next versions with JupyterLab 0.33, in a couple of days.

**Pull request merged**
