### PR TITLE
Add mybinder badge

### PR DESCRIPTION
**Pull request by ian-r-rose**
Adds mybinder and GitHub buttons to the toolbar. The mybinder button is only active if the user is currently viewing a repository that contains one of the special files listed in repo2docker.

Still not working: specifying other branches than `master`, launching binder with more a more specific subdirectory.
cc. @choldgraf @yuvipanda.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Screengrab:
image

**Comment by willingc** [comment]
@ian-r-rose Lovely 👍 Any chance that you can make the icons look more clickable (perhaps that was what the latest style tweak did)? Great job.

**Comment by ian-r-rose** [comment]
The icons gain a border upon mouse hover (in the same way that buttons in the filebrowser do).

**Comment by choldgraf** [comment]
this is super cool! thanks @ian-r-rose ! A couple quick thoughts:

1. We should (in a diff issue) have a conversation about what kind of "official" binder buttons we should put out there. E.g., I like @ian-r-rose using the binder logo here...
2. One trick here is that the binder build files are quite common *outside* of a binder context (e.g. requirements.txt). I'm a little concerned that the plugin will catch these cases where the repo still isn't binderable... what do you all think?

**Comment by ian-r-rose** [comment]
1. Agreed. For prior work on this, see the Jupyter branding guidelines [here](https://github.com/jupyter/design). In general, we have said it is fine to use the logo if advertising integration with the project, but not to use it for other purposes. Modifying it is also against the guidelines. (As I have done slightly by removing the `binder` text!).

2. Yes, that is tricky, and would require much more introspection into the repository. Here, I am only checking if files with those names exist, and it will definitely catch cases where binder will not work. You probably have a better idea of how to improve the screening than I.

**Comment by willingc** [comment]
2. @ian-r-rose, if I understand correctly the jupyterlab user could choose whether or not to install/disable this feature. If so, then the user can opt out if desired. Perhaps adding to a message on hover that it builds based on current repo contents and YMMV (i.e. user would need to make sure the contents are binderable).

**Comment by choldgraf** [comment]
That's a good point about people being able to opt out @willingc ... I like the idea of it being enabled by default though, it'll hopefully let some people know about the binder world!

**Comment by ian-r-rose** [comment]
2. @willingc, it is currently enabled in this plugin. I have been thinking through how to make it more configurable though, including
* whether to make it disabled
* the ability to set a different deployment of binderhub

**Comment by ian-r-rose** [comment]
(Since this is an extension to JupyterLab, none of it is installed by default in a basic `pip install jupyterlab`)

**Comment by willingc** [comment]
Thanks @ian-r-rose. For now, I wouldn't be too concerned about 2 until we can spec out what would specifically be needed.

**Pull request merged**
